### ISSUE TITLE
今上がっている構想のドキュメント化

### ISSUE THREAD

**Issue by KeitoTobi1** [omnius-labs/xeus#127]

**Comment by lyrise** [comment]
単純に色々ドキュメント化面倒だなとなってます。

**Comment by lyrise** [comment]
GitHubのIssuesをProjectsで管理してそれぞれ詳細に書けば、直近やりたい事とタスク化が可能かなと思った

**Comment by lyrise** [comment]
https://github.com/omnius-labs/xeus/projects
とりあえずこんな感じに描いてみた
